[package]
name = "csv"
<<<<<<< HEAD
version = "0.6.1"
=======
version = "0.6.1"
>>>>>>> dev
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
